apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  ring_buffer_capacity: {{ .Values.ringBufferCapacity | quote }}
  socket_path: {{ .Values.socketPath | quote }}
