{{- if .Values.metrics.serviceEnabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    {{- with .Values.extraLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: {{ .Values.metrics.port | quote }}
    prometheus.io/path: "/metrics"
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
  ports:
    - name: metrics
      port: {{ .Values.metrics.port }}
      targetPort: metrics
      protocol: TCP
{{- end }}
